// Generated by create-api-home — live runmoa Storefront config (pub key only, browser-safe).
window.RUNMOA = {
  "useApi": true,
  "siteHost": "ootbstudio.runmoa.com",
  "storefrontKey": "moa_pub_HfJsUJhGkaTyMr18NnZdvKLasa09BqJewxie0GdRJt-fBSmxxxhV4bLITAXIgED6",
  "limit": 48
};
